package com.devtence.will.dev.models;

import java.util.List;

/**
 * Wrapper Class for basic listing functionality for Endpoints, this class also provides an easy way to access
 * the total amount of elements generated by the query for pagination purposes and the cursor index generated by the
 * Google Cloud Datastore.
 *
 * @author sorcerer
 * @since 2015-10-12
 */
public class ListItem {

    private Integer totalCount;
    private String cursor;
    private List items;

    /**
     * Constructor
     */
    public ListItem() {
        this.totalCount = 0;
    }

    /**
     * Getter for item list count.
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * Setter for item list count.
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * Getter for the Google Cloud Datastore cursor.
     */
    public String getCursor() {
        return cursor;
    }

    public void setCursor(String cursor) {
        this.cursor = cursor;
    }

    public List getItems() {
        return items;
    }

    public void setItems(List items) {
        this.items = items;
    }
}
